###
# Sets up and configures Supervisor for Celery and Celerybeat
##
- name: create Supervisor template for Celery to run
  template: src=supervisor_celery.conf.j2
            dest=/etc/supervisor/conf.d/{{ app_name }}_celery.conf
  sudo: yes

- name: create Supervisor template for Celerybeat to run
  template: src=supervisor_celerybeat.conf.j2
            dest=/etc/supervisor/conf.d/{{ app_name }}_celerybeat.conf
  sudo: yes

- name: stop supervisor for celery
  command: service supervisor stop
  sudo: yes

- name: pause for restart to take effect
  pause: seconds=2

- name: start supervisor for celery
  command: service supervisor start
  sudo: yes
